### ISSUE TITLE
Add automatic [instrumental], [intro] and [outro]

### ISSUE THREAD

**Issue by incidentist** [incidentist/the_tuul#4]
Detect long stretches without singing, and add [INTRO], [INSTRUMENTAL] and [OUTRO] screens as appropriate.

**Comment by WicCaesar** [comment]
Musixmatch tags these with hashes and the corresponding part of the music before a set of verses. For instance:

```
#PRECHORUS
Too high, can't come down
It's in the air and it's all around
Can you feel me now?

#CHORUS
With a taste of your lips, I'm on a ride
You're toxic, I'm slippin' under
With a taste of a poison paradise
I'm addicted to you
Don't you know that you're toxic?
```

They have the following structures: `#INTRO #VERSE #PRE-CHORUS #CHORUS #HOOK #BRIDGE #OUTRO`. You don't need all those, right? `#INSTRUMENTAL` is a good one.

I know you're trying to implement it automatically, but I ask you to consider _not to apply it automatically_ to every video; leaving the choice to the user if they want those tags on screen. I wouldn't like them to appear automatically in lyrics that are not in English, for instance. The word _"outro"_ in Portuguese means _"other"_, no one would associate it with the ending of a song, we simply don't have a name for it.

And while you don't implement automatic detection, I think you could just guide the user to apply it along with the lyrics, since we're editing them anyway. So when the instrumental part begins, the user just hits the spacebar on the line that says `#INSTRUMENTAL` (they themselves wrote there, minimising any risk of _"misdetection"_).

**Comment by WicCaesar** [comment]
> I'm not familiar with Musixmatch

The controls in their synchronisation screen are so good! I was surprised.

https://i.imgur.com/VpTlywt.png
This white button with a down arrow is equivalent to the space bar at Tüül.

https://i.imgur.com/aA5IIfe.png
I love these + - buttons that allow us to fine adjust the starting of a new line.
